export const GET_CLINET_START = "GET_CLINET_START";
export const GET_CLINET_SUCCESS = "GET_CLINET_SUCCESS";
export const GET_CLINET_FAILURE = "GET_CLINET_FAILURE";

export const GET_CLINET_DATA_START = "GET_CLINET_DATA_START";
export const GET_CLINET_DATA_SUCCESS = "GET_CLINET_DATA_SUCCESS";
export const GET_CLINET_DATA_FAILURE = "GET_CLINET_DATA_FAILURE";

export const GET_LM_REWARD_DATA_START = "GET_LM_REWARD_DATA_START";
export const GET_LM_REWARD_DATA_SUCCESS = "GET_LM_REWARD_DATA_SUCCESS";
export const GET_LM_REWARD_DATA_FAILURE = "GET_LM_REWARD_DATA_FAILURE";


export const GET_FIND_SHOPPER_DATA_START = "GET_FIND_SHOPPER_DATA_START";
export const GET_FIND_SHOPPER_DATA_SUCCESS = "GET_FIND_SHOPPER_DATA_SUCCESS";
export const GET_FIND_SHOPPER_DATA_FAILURE = "GET_FIND_SHOPPER_DATA_FAILURE";

export const GET_FIND_SHOPPER_DATA_BY_ID_START = "GET_FIND_SHOPPER_DATA_BY_ID_START";
export const GET_FIND_SHOPPER_DATA_BY_ID_SUCCESS = "GET_FIND_SHOPPER_DATA_BY_ID_SUCCESS";
export const GET_FIND_SHOPPER_DATA_BY_ID_FAILURE = "GET_FIND_SHOPPER_DATA_BY_ID_FAILURE";

export const GET_CLIENT_STORES_DATA_START = "GET_CLIENT_STORES_DATA_START";
export const GET_CLIENT_STORES_DATA_SUCCESS = "GET_CLIENT_STORES_DATA_SUCCESS";
export const GET_CLIENT_STORES_DATA_FAILURE = "GET_CLIENT_STORES_DATA_FAILURE";

export const GET_REWARD_TYPES_DATA_START = "GET_REWARD_TYPES_DATA_START";
export const GET_REWARD_TYPES_DATA_SUCCESS = "GET_REWARD_TYPES_DATA_SUCCESS";
export const GET_REWARD_TYPES_DATA_FAILURE = "GET_REWARD_TYPES_DATA_FAILURE";

export const UPDATE_FIND_SHOPPER_DATA_BY_ID_START = "UPDATE_FIND_SHOPPER_DATA_BY_ID_START";
export const UPDATE_FIND_SHOPPER_DATA_BY_ID_SUCCESS = "UPDATE_FIND_SHOPPER_DATA_BY_ID_SUCCESS";
export const UPDATE_FIND_SHOPPER_DATA_BY_ID_FAILURE = "UPDATE_FIND_SHOPPER_DATA_BY_ID_FAILURE";

export const GET_USER_CLIPS_REDEMPTIONS_START = "GET_USER_CLIPS_REDEMPTIONS_START";
export const GET_USER_CLIPS_REDEMPTIONS_SUCCESS = "GET_USER_CLIPS_REDEMPTIONS_SUCCESS";
export const GET_USER_CLIPS_REDEMPTIONS_FAILURE = "GET_USER_CLIPS_REDEMPTIONS_FAILURE";

export const GET_USER_REWARD_COUPONS_START = "GET_USER_REWARD_COUPONS_START";
export const GET_USER_REWARD_COUPONS_SUCCESS = "GET_USER_REWARD_COUPONS_SUCCESS";
export const GET_USER_REWARD_COUPONS_FAILURE = "GET_USER_REWARD_COUPONS_FAILURE";

export const GET_USER_HISTORY_START = "GET_USER_HISTORY_START";
export const GET_USER_HISTORY_SUCCESS = "GET_USER_HISTORY_SUCCESS";
export const GET_USER_HISTORY_FAILURE = "GET_USER_HISTORY_FAILURE";

export const GET_USER_BASKET_TRANSACTION_START = "GET_USER_BASKET_TRANSACTION_START";
export const GET_USER_BASKET_TRANSACTION_SUCCESS = "GET_USER_BASKET_TRANSACTION_SUCCESS";
export const GET_USER_BASKET_TRANSACTION_FAILURE = "GET_USER_BASKET_TRANSACTION_FAILURE";

export const GET_USER_PURCHASE_PRODUCT_START = "GET_USER_PURCHASE_PRODUCT_START";
export const GET_USER_PURCHASE_PRODUCT_SUCCESS = "GET_USER_PURCHASE_PRODUCT_SUCCESS";
export const GET_USER_PURCHASE_PRODUCT_FAILURE = "GET_USER_PURCHASE_PRODUCT_FAILURE";

export const GET_USER_PURCHASE_COUPONS_START = "GET_USER_PURCHASE_COUPONS_START";
export const GET_USER_PURCHASE_COUPONS_SUCCESS = "GET_USER_PURCHASE_COUPONS_SUCCESS";
export const GET_USER_PURCHASE_COUPONS_FAILURE = "GET_USER_PURCHASE_COUPONS_FAILURE";

export const GET_USER_LMREWARDS_MEMBERNUMBER_START = "GET_USER_LMREWARDS_MEMBERNUMBER_START";
export const GET_USER_LMREWARDS_MEMBERNUMBER_SUCCESS = "GET_USER_LMREWARDS_MEMBERNUMBER_SUCCESS";
export const GET_USER_LMREWARDS_MEMBERNUMBER_FAILURE = "GET_USER_LMREWARDS_MEMBERNUMBER_FAILURE";

export const GET_FIND_MEMBERNUMBER_START = "GET_FIND_MEMBERNUMBER_START";
export const GET_FIND_MEMBERNUMBER_SUCCESS = "GET_FIND_MEMBERNUMBER_SUCCESS";
export const GET_FIND_MEMBERNUMBER_FAILURE = "GET_FIND_MEMBERNUMBER_FAILURE";

export const SAVE_USER_POINTS_START = "SAVE_USER_POINTS_START";
export const SAVE_USER_POINTS_SUCCESS = "SAVE_USER_POINTS_SUCCESS";
export const SAVE_USER_POINTS_FAILURE = "SAVE_USER_POINTS_FAILURE";


export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const PAGINATION_START = "PAGINATION_START";
export const PAGINATION_SUCCESS = "PAGINATION_SUCCESS";
export const PAGINATION_FAILURE = "PAGINATION_FAILURE";

export const CREATE_SHOPPER_GROUPS_START = "CREATE_SHOPPER_GROUPS_START";
export const CREATE_SHOPPER_GROUPS_SUCCESS = "CREATE_SHOPPER_GROUPS_SUCCESS";
export const CREATE_SHOPPER_GROUPS_FAILURE = "CREATE_SHOPPER_GROUPS_FAILURE";

export const GET_USER_GROUPS_START = "GET_USER_GROUPS_START";
export const GET_USER_GROUPS_SUCCESS = "GET_USER_GROUPS_SUCCESS";

export const GET_USER_GROUPS_FAILURE = "GET_USER_GROUPS_FAILURE";

export const GET_USER_AVAILABLE_GROUPS_START = "GET_USER_AVAILABLE_GROUPS_START";
export const GET_USER_AVAILABLE_GROUPS_SUCCESS = "GET_USER_AVAILABLE_GROUPS_SUCCESS";

export const GET_USER_AVAILABLE_GROUPS_FAILURE = "GET_USER_AVAILABLE_GROUPS_FAILURE";


export const ADD_USER_AVAILABLE_GROUPS_START = "ADD_USER_AVAILABLE_GROUPS_START";
export const ADD_USER_AVAILABLE_GROUPS_SUCCESS = "ADD_USER_AVAILABLE_GROUPS_SUCCESS";

export const ADD_USER_AVAILABLE_GROUPS_FAILURE = "ADD_USER_AVAILABLE_GROUPS_FAILURE";

export const CREATE_SHOPPER_START = "CREATE_SHOPPER_START";
export const CREATE_SHOPPER_SUCCESS = "CREATE_SHOPPER_SUCCESS";
export const CREATE_SHOPPER_FAILURE = "CREATE_SHOPPER_FAILURE";

export const GET_USERTYPES_START = "GET_USERTYPES_START";
export const GET_USERTYPES_SUCCESS = "GET_USERTYPES_SUCCESS";
export const GET_USERTYPES_FAILURE = "GET_USERTYPES_FAILURE";

export const GET_ROLES_START = "GET_ROLES_START";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";

export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";

export const GET_GROUP_ANALYSIS_START = "GET_GROUP_ANALYSIS_START";
export const GET_GROUP_ANALYSIS_SUCCESS = "GET_GROUP_ANALYSIS_SUCCESS";
export const GET_GROUP_ANALYSIS_FAILURE = "GET_GROUP_ANALYSIS_FAILURE";

export const GET_ALL_TIME_PRODUCTS_START = "GET_ALL_TIME_PRODUCTS_START";
export const GET_ALL_TIME_PRODUCTS_SUCCESS = "GET_ALL_TIME_PRODUCTS_SUCCESS";
export const GET_ALL_TIME_PRODUCTS_FAILURE = "GET_ALL_TIME_PRODUCTS_FAILURE";

export const GET_TOP_PRODUCTS_START = "GET_TOP_PRODUCTS_START";
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS";
export const GET_TOP_PRODUCTS_FAILURE = "GET_TOP_PRODUCTS_FAILURE";

export const GET_ALL_SHOPPERS_DATA_START = "GET_ALL_SHOPPERS_DATA_START";
export const GET_ALL_SHOPPERS_DATA_SUCCESS = "GET_ALL_SHOPPERS_DATA_SUCCESS";
export const GET_ALL_SHOPPERS_DATA_FAILURE = "GET_ALL_SHOPPERS_DATA_FAILURE";

export const DOWNLOAD_SHOPPERS_START = "DOWNLOAD_SHOPPERS_START";
export const DOWNLOAD_SHOPPERS_SUCCESS = "DOWNLOAD_SHOPPERS_SUCCESS";
export const DOWNLOAD_SHOPPERS_FAILURE = "DOWNLOAD_SHOPPERS_FAILURE";

export const CREATE_UPC_LIST_GROUP_STRAT = "CREATE_UPC_LIST_GROUP_STRAT";
export const CREATE_UPC_LIST_GROUP_SUCCESS = "CREATE_UPC_LIST_GROUP_SUCCESS";
export const CREATE_UPC_LIST_GROUP_FAILURE = "CREATE_UPC_LIST_GROUP_FAILURE";

export const CREATE_ZIPCODES_LIST_GROUP_STRAT = "CREATE_ZIPCODES_LIST_GROUP_STRAT";
export const CREATE_ZIPCODES_LIST_GROUP_SUCCESS = "CREATE_ZIPCODES_LIST_GROUP_SUCCESS";
export const CREATE_ZIPCODES_LIST_GROUP_FAILURE = "CREATE_ZIPCODES_LIST_GROUP_FAILURE";

export const CREATE_LOSTSHOPPER_GROUP_STRAT = "CREATE_LOSTSHOPPER_GROUP_STRAT";
export const CREATE_LOSTSHOPPER_GROUP_SUCCESS = "CREATE_LOSTSHOPPER_GROUP_SUCCESS";
export const CREATE_LOSTSHOPPER_GROUP_FAILURE = "CREATE_LOSTSHOPPER_GROUP_FAILURE";

export const GET_TOP_SHOPPER_START = "GET_TOP_SHOPPER_START";
export const GET_TOP_SHOPPER_SUCCESS = "GET_TOP_SHOPPER_SUCCESS";
export const GET_TOP_SHOPPER_FAILURE = "GET_TOP_SHOPPER_FAILURE";

export const GET_PRODUCT_CATEGORIES_START = "GET_PRODUCT_CATEGORIES_START";
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS";
export const GET_PRODUCT_CATEGORIES_FAILURE = "GET_PRODUCT_CATEGORIES_FAILURE";

export const GET_ADVANCED_SHOPPER_SEARCH_START = "GET_ADVANCED_SHOPPER_SEARCH_START";
export const GET_ADVANCED_SHOPPER_SEARCH_SUCCESS = "GET_ADVANCED_SHOPPER_SEARCH_SUCCESS";
export const GET_ADVANCED_SHOPPER_SEARCH_FAILURE = "GET_ADVANCED_SHOPPER_SEARCH_FAILURE";

export const GET_SHOPPER_BY_UPCS_START = "GET_SHOPPER_BY_UPCS_START";
export const GET_SHOPPER_BY_UPCS_SUCCESS = "GET_SHOPPER_BY_UPCS_SUCCESS";
export const GET_SHOPPER_BY_UPCS_FAILURE = "GET_SHOPPER_BY_UPCS_FAILURE";

export const GET_SHOPPER_PRODUCT_START = "GET_SHOPPER_PRODUCT_START";
export const GET_SHOPPER_PRODUCT_SUCCESS = "GET_SHOPPER_PRODUCT_SUCCESS";
export const GET_SHOPPER_PRODUCT_FAILURE = "GET_SHOPPER_PRODUCT_FAILURE";

export const GET_SEARCH_COUNT_START = "GET_SEARCH_COUNT_START";
export const GET_SEARCH_COUNT_SUCCESS = "GET_SEARCH_COUNT_SUCCESS";
export const GET_SEARCH_COUNT_FAILURE = "GET_SEARCH_COUNT_FAILURE";


export const GET_SEARCH_CREATE_START = "GET_SEARCH_CREATE_START";
export const GET_SEARCH_CREATE_SUCCESS = "GET_SEARCH_CREATE_SUCCESS";
export const GET_SEARCH_CREATE_FAILURE = "GET_SEARCH_CREATE_FAILURE";

export const UPLOAD_SHOPPERS_START = "UPLOAD_SHOPPERS_START";
export const UPLOAD_SHOPPERS_SUCCESS = "UPLOAD_SHOPPERS_SUCCESS";
export const UPLOAD_SHOPPERS_FAILURE = "UPLOAD_SHOPPERS_FAILURE";

export const GET_NEWS_CATAGORY_START = "GET_NEWS_CATAGORY_START";
export const GET_NEWS_CATAGORY_SUCCESS = "GET_NEWS_CATAGORY_SUCCESS";
export const GET_NEWS_CATAGORY_FAILURE = "GET_NEWS_CATAGORY_FAILURE";

export const GET_FIND_COUPON_START = "GET_FIND_COUPON_START";
export const GET_FIND_COUPON_SUCCESS = "GET_FIND_COUPON_SUCCESS";
export const GET_FIND_COUPON_FAILURE = "GET_FIND_COUPON_FAILURE";

export const CREATE_BASKET_COUPON_START = "CREATE_BASKET_COUPON_START";
export const CREATE_BASKET_COUPON_SUCCESS = "CREATE_BASKET_COUPON_SUCCESS";
export const CREATE_BASKET_COUPON_FAILURE = "CREATE_BASKET_COUPON_FAILURE";

export const CREATE_UPC_COUPON_START = "CREATE_UPC_COUPON_START";
export const CREATE_UPC_COUPON_SUCCESS = "CREATE_UPC_COUPON_SUCCESS";
export const CREATE_UPC_COUPON_FAILURE = "CREATE_UPC_COUPON_SUCCESS";


